import React from 'react';
import { Link } from 'react-router-dom';
import {
  X, FileText, Download, CheckCircle, MapPin, Calendar,
  Users, Car, Flame, CloudRain, AlertTriangle, ArrowLeft, ArrowRight,
  ArrowLeftRight, ShieldAlert, ExternalLink
} from 'lucide-react';
import type { Incident } from '../types';
import { downloadIncidentReport } from '../utils/reportGenerator';

interface AnalysisReportModalProps {
  isOpen: boolean;
  incident: Incident;
  onClose: () => void;
}

export const AnalysisReportModal: React.FC<AnalysisReportModalProps> = ({
  isOpen,
  incident,
  onClose,
}) => {
  if (!isOpen) return null;

  const stats = incident.stats || {
    totalPeople: 48,
    peopleDelta: 3,
    totalVehicles: 24,
    vehiclesDelta: 2,
    fireIncidents: { major: 1, minor: 1, hazardous: 1 },
    entryExitPoints: { total: 4, entry: 2, exit: 2 },
    damagedAreas: { total: 2, details: 'Bridge Section + Road' },
  };

  const detected = incident.detectedConditions || {
    structuralDamage: true,
    fire: true,
    smoke: true,
    humanPresence: true,
    vehiclePresence: true,
    entryExit: true,
  };

  const overall = incident.overallCondition || {
    level: 'CRITICAL',
    title: 'CRITICAL',
    description:
      'The analysed scene indicates significant structural damage with active fire activity and multiple detected entities. The affected area should be inspected and secured immediately.',
  };

  const observations = incident.keyObservations || [
    'Structural damage detected on the bridge section.',
    'Active fire detected near the roadway.',
    'Multiple vehicles identified in the affected zone.',
    'Human presence detected within the incident area.',
    'Multiple entry and exit points identified.',
  ];

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto animate-fadeIn">
      {/* Modal Box */}
      <div className="relative w-full max-w-4xl my-auto bg-[#060b18] border border-[#142854] rounded-2xl shadow-[0_0_50px_rgba(0,0,0,0.95)] overflow-hidden flex flex-col">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#122245] bg-[#070e20]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-600/20 border border-cyan-400/40 flex items-center justify-center text-cyan-400 shadow-[0_0_15px_rgba(0,210,255,0.25)]">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white tracking-tight">Analysis Report</h2>
              <p className="text-xs text-slate-400">Comprehensive incident analysis generated by AeroMesh</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-950/70 border border-emerald-500/50 text-emerald-400 text-xs font-semibold">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              <span>{incident.status}</span>
            </div>

            <div className="text-xs font-mono text-slate-400 hidden sm:block">
              Incident ID: <span className="text-cyan-400">{incident.id}</span>
            </div>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-[#0f1d3d] transition-colors"
              title="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Content */}
        <div className="p-6 space-y-6 overflow-y-auto max-h-[75vh]">
          
          {/* Section 1: Incident Overview */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-blue-600 text-white font-bold text-[11px] flex items-center justify-center">
                1
              </span>
              <h3 className="text-sm font-bold text-white tracking-wide">Incident Overview</h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {/* Incident ID */}
              <div className="flex items-center gap-3 p-3.5 rounded-xl bg-[#091228] border border-[#142650]">
                <div className="w-8 h-8 rounded-lg bg-[#0d1c40] flex items-center justify-center text-cyan-400">
                  <FileText className="w-4 h-4" />
                </div>
                <div>
                  <p className="text-[10px] uppercase font-semibold text-slate-400">Incident ID</p>
                  <p className="text-xs font-bold text-white font-mono">{incident.id}</p>
                </div>
              </div>

              {/* Incident Name */}
              <div className="flex items-center gap-3 p-3.5 rounded-xl bg-[#091228] border border-[#142650]">
                <div className="w-8 h-8 rounded-lg bg-[#0d1c40] flex items-center justify-center text-cyan-400">
                  <CheckCircle className="w-4 h-4" />
                </div>
                <div className="truncate">
                  <p className="text-[10px] uppercase font-semibold text-slate-400">Incident Name</p>
                  <p className="text-xs font-bold text-white truncate">{incident.name}</p>
                </div>
              </div>

              {/* Analysis Status */}
              <div className="flex items-center gap-3 p-3.5 rounded-xl bg-[#091228] border border-[#142650]">
                <div className="w-8 h-8 rounded-lg bg-emerald-950/60 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
                  <CheckCircle className="w-4 h-4" />
                </div>
                <div>
                  <p className="text-[10px] uppercase font-semibold text-slate-400">Analysis Status</p>
                  <p className="text-xs font-bold text-emerald-400">Completed</p>
                </div>
              </div>

              {/* Location */}
              <div className="flex items-center gap-3 p-3.5 rounded-xl bg-[#091228] border border-[#142650] sm:col-span-2">
                <div className="w-8 h-8 rounded-lg bg-[#0d1c40] flex items-center justify-center text-cyan-400 flex-shrink-0">
                  <MapPin className="w-4 h-4" />
                </div>
                <div className="truncate">
                  <p className="text-[10px] uppercase font-semibold text-slate-400">Location</p>
                  <p className="text-xs font-bold text-white truncate">{incident.location}</p>
                </div>
              </div>

              {/* Date & Time */}
              <div className="flex items-center gap-3 p-3.5 rounded-xl bg-[#091228] border border-[#142650]">
                <div className="w-8 h-8 rounded-lg bg-[#0d1c40] flex items-center justify-center text-cyan-400">
                  <Calendar className="w-4 h-4" />
                </div>
                <div>
                  <p className="text-[10px] uppercase font-semibold text-slate-400">Date &amp; Time</p>
                  <p className="text-xs font-bold text-white font-mono">{incident.date} • {incident.time}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Section 2: Entity Detection Summary */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-blue-600 text-white font-bold text-[11px] flex items-center justify-center">
                2
              </span>
              <h3 className="text-sm font-bold text-white tracking-wide">Entity Detection Summary</h3>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2.5">
              {/* People */}
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] text-center space-y-1">
                <div className="flex items-center justify-center gap-1.5 text-slate-400 text-[11px]">
                  <Users className="w-3.5 h-3.5 text-cyan-400" />
                  <span>People</span>
                </div>
                <div className="text-xl font-bold text-white font-mono">{stats.totalPeople}</div>
                <div className="text-[10px] text-emerald-400 font-bold">↑ +{stats.peopleDelta}</div>
              </div>

              {/* Vehicles */}
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] text-center space-y-1">
                <div className="flex items-center justify-center gap-1.5 text-slate-400 text-[11px]">
                  <Car className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Vehicles</span>
                </div>
                <div className="text-xl font-bold text-white font-mono">{stats.totalVehicles}</div>
                <div className="text-[10px] text-emerald-400 font-bold">↑ +{stats.vehiclesDelta}</div>
              </div>

              {/* Fire */}
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] text-center space-y-1">
                <div className="flex items-center justify-center gap-1.5 text-slate-400 text-[11px]">
                  <Flame className="w-3.5 h-3.5 text-rose-400" />
                  <span>Fire Incidents</span>
                </div>
                <div className="text-xl font-bold text-white font-mono">
                  {stats.fireIncidents.major + stats.fireIncidents.minor + stats.fireIncidents.hazardous}
                </div>
                <div className="text-[9px] text-rose-400 font-mono">
                  Major: {stats.fireIncidents.major} | Minor: {stats.fireIncidents.minor}
                </div>
              </div>

              {/* Smoke */}
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] text-center space-y-1">
                <div className="flex items-center justify-center gap-1.5 text-slate-400 text-[11px]">
                  <CloudRain className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Smoke</span>
                </div>
                <div className="text-xl font-bold text-white font-mono">5</div>
                <div className="text-[10px] text-emerald-400 font-bold">↑ +1</div>
              </div>

              {/* Damaged Areas */}
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] text-center space-y-1">
                <div className="flex items-center justify-center gap-1.5 text-slate-400 text-[11px]">
                  <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
                  <span>Damaged Areas</span>
                </div>
                <div className="text-xl font-bold text-white font-mono">{stats.damagedAreas.total}</div>
                <div className="text-[9px] text-slate-400 truncate">{stats.damagedAreas.details}</div>
              </div>

              {/* Entry Points */}
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] text-center space-y-1">
                <div className="flex items-center justify-center gap-1.5 text-slate-400 text-[11px]">
                  <ArrowLeft className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Entry Points</span>
                </div>
                <div className="text-xl font-bold text-white font-mono">{stats.entryExitPoints.entry}</div>
                <div className="text-[9px] text-slate-400">(Entry / Exit)</div>
              </div>

              {/* Exit Points */}
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] text-center space-y-1">
                <div className="flex items-center justify-center gap-1.5 text-slate-400 text-[11px]">
                  <ArrowRight className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Exit Points</span>
                </div>
                <div className="text-xl font-bold text-white font-mono">{stats.entryExitPoints.exit}</div>
                <div className="text-[9px] text-slate-400">(Entry / Exit)</div>
              </div>
            </div>
          </div>

          {/* Section 3: Detected Conditions */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-blue-600 text-white font-bold text-[11px] flex items-center justify-center">
                3
              </span>
              <h3 className="text-sm font-bold text-white tracking-wide">Detected Conditions</h3>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5">
              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] flex flex-col items-center justify-center text-center space-y-1.5">
                <div className="w-8 h-8 rounded-lg bg-blue-950/60 border border-blue-500/30 flex items-center justify-center text-cyan-400">
                  <AlertTriangle className="w-4 h-4" />
                </div>
                <p className="text-[11px] font-semibold text-slate-200">Structural Damage</p>
                <span className={`inline-flex items-center gap-1 text-[10px] font-bold ${detected.structuralDamage ? 'text-emerald-400' : 'text-slate-500'}`}>
                  {detected.structuralDamage && <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />}
                  {detected.structuralDamage ? 'Detected' : 'None'}
                </span>
              </div>

              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] flex flex-col items-center justify-center text-center space-y-1.5">
                <div className="w-8 h-8 rounded-lg bg-blue-950/60 border border-blue-500/30 flex items-center justify-center text-rose-400">
                  <Flame className="w-4 h-4" />
                </div>
                <p className="text-[11px] font-semibold text-slate-200">Fire</p>
                <span className={`inline-flex items-center gap-1 text-[10px] font-bold ${detected.fire ? 'text-emerald-400' : 'text-slate-500'}`}>
                  {detected.fire && <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />}
                  {detected.fire ? 'Detected' : 'None'}
                </span>
              </div>

              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] flex flex-col items-center justify-center text-center space-y-1.5">
                <div className="w-8 h-8 rounded-lg bg-blue-950/60 border border-blue-500/30 flex items-center justify-center text-cyan-400">
                  <CloudRain className="w-4 h-4" />
                </div>
                <p className="text-[11px] font-semibold text-slate-200">Smoke</p>
                <span className={`inline-flex items-center gap-1 text-[10px] font-bold ${detected.smoke ? 'text-emerald-400' : 'text-slate-500'}`}>
                  {detected.smoke && <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />}
                  {detected.smoke ? 'Detected' : 'None'}
                </span>
              </div>

              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] flex flex-col items-center justify-center text-center space-y-1.5">
                <div className="w-8 h-8 rounded-lg bg-blue-950/60 border border-blue-500/30 flex items-center justify-center text-cyan-400">
                  <Users className="w-4 h-4" />
                </div>
                <p className="text-[11px] font-semibold text-slate-200">Human Presence</p>
                <span className={`inline-flex items-center gap-1 text-[10px] font-bold ${detected.humanPresence ? 'text-emerald-400' : 'text-slate-500'}`}>
                  {detected.humanPresence && <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />}
                  {detected.humanPresence ? 'Detected' : 'None'}
                </span>
              </div>

              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] flex flex-col items-center justify-center text-center space-y-1.5">
                <div className="w-8 h-8 rounded-lg bg-blue-950/60 border border-blue-500/30 flex items-center justify-center text-cyan-400">
                  <Car className="w-4 h-4" />
                </div>
                <p className="text-[11px] font-semibold text-slate-200">Vehicle Presence</p>
                <span className={`inline-flex items-center gap-1 text-[10px] font-bold ${detected.vehiclePresence ? 'text-emerald-400' : 'text-slate-500'}`}>
                  {detected.vehiclePresence && <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />}
                  {detected.vehiclePresence ? 'Detected' : 'None'}
                </span>
              </div>

              <div className="p-3 rounded-xl bg-[#091228] border border-[#142650] flex flex-col items-center justify-center text-center space-y-1.5">
                <div className="w-8 h-8 rounded-lg bg-blue-950/60 border border-blue-500/30 flex items-center justify-center text-cyan-400">
                  <ArrowLeftRight className="w-4 h-4" />
                </div>
                <p className="text-[11px] font-semibold text-slate-200">Entry / Exit Points</p>
                <span className={`inline-flex items-center gap-1 text-[10px] font-bold ${detected.entryExit ? 'text-emerald-400' : 'text-slate-500'}`}>
                  {detected.entryExit && <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />}
                  {detected.entryExit ? 'Detected' : 'None'}
                </span>
              </div>
            </div>
          </div>

          {/* Section 4 & 5 Grid: Overall Condition & Key Observations */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            
            {/* Section 4: Overall Condition */}
            <div className="p-4 rounded-xl bg-[#081024] border border-[#142650] space-y-3">
              <div className="flex items-center gap-2">
                <span className="w-5 h-5 rounded-full bg-blue-600 text-white font-bold text-[11px] flex items-center justify-center">
                  4
                </span>
                <h3 className="text-sm font-bold text-white tracking-wide">Overall Condition</h3>
              </div>

              {/* Critical Alert Card */}
              <div className="p-3.5 rounded-xl bg-gradient-to-r from-rose-950/80 to-rose-900/40 border border-rose-500/50 flex items-center gap-3 shadow-[0_0_20px_rgba(244,63,94,0.15)]">
                <div className="w-10 h-10 rounded-xl bg-rose-900/60 border border-rose-400/60 flex items-center justify-center text-rose-300 flex-shrink-0">
                  <ShieldAlert className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-extrabold text-white tracking-wide">{overall.level}</h4>
                  <p className="text-[11px] text-rose-300">Immediate attention recommended</p>
                </div>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed">
                {overall.description}
              </p>
            </div>

            {/* Section 5: Key Observations */}
            <div className="p-4 rounded-xl bg-[#081024] border border-[#142650] space-y-3">
              <div className="flex items-center gap-2">
                <span className="w-5 h-5 rounded-full bg-blue-600 text-white font-bold text-[11px] flex items-center justify-center">
                  5
                </span>
                <h3 className="text-sm font-bold text-white tracking-wide">Key Observations</h3>
              </div>

              <ul className="space-y-2 text-xs text-slate-300">
                {observations.map((obs, idx) => (
                  <li key={idx} className="flex items-start gap-2.5">
                    <span className="w-2 h-2 rounded-full bg-cyan-400 shadow-[0_0_8px_#00d2ff] mt-1 flex-shrink-0" />
                    <span>{obs}</span>
                  </li>
                ))}
              </ul>
            </div>

          </div>

        </div>

        {/* Modal Footer */}
        <div className="px-6 py-4 border-t border-[#122245] bg-[#070e20] flex items-center justify-between gap-3">
          <Link
            to={`/report/${incident.id}`}
            onClick={onClose}
            className="flex items-center gap-1.5 text-xs font-semibold text-cyan-400 hover:text-cyan-300 transition-colors"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            <span>Open Full Page View</span>
          </Link>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={onClose}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[#0c1836] border border-[#1c3364] hover:border-slate-400 text-xs font-semibold text-slate-300 hover:text-white transition-colors"
            >
              <X className="w-3.5 h-3.5" />
              <span>Close</span>
            </button>

            <button
              type="button"
              onClick={() => downloadIncidentReport(incident)}
              className="flex items-center gap-2 px-5 py-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 text-white text-xs font-bold shadow-[0_0_20px_rgba(0,210,255,0.4)] transition-all cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download Report</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
